pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["chargedischargeunits.htm","Charge/Discharge Units","Charge/Discharge Units Where possible the charge and discharge rate is given in mW. However, due to the limitations of some batteries this is not ...",""],
["hid_autorun.htm","Starting BatteryMon when Windows starts","Auto-run applications This page gives a brief description of how an application can be setup to run automatically when Windows starts. Method1 – C...",""],
["hid_batinfo.htm","Battery information window","Battery Information All available information about each available battery is displayed in this window. How accurate this information is depends o...",""],
["hid_commandline.htm","Command line options","Command line options There are two command line options. If no command line option is specified, BatteryMon starts normally. /r BatteryMon will au...",""],
["hid_config.htm","Configuration","Configuration Sample time: This setting determines how often BatteryMon should sample the battery information. If auto logging is turned on, this ...",""],
["hid_contacts.htm","Contacting PassMark Software","Contacting PassMark Software On the Web You can contact PassMark on the web at http://www.passmark.com E-Mail For technical support questions, sug...",""],
["hid_copyright.htm","Copyright and License","Copyright &#38; License information Copyright &#38; End User license This End-User License Agreement (&#8220;EULA&#8221;) is for the PassMark BatteryMon software. EUL...",""],
["hid_display.htm","Understanding the display","BatteryMon Display Graph: The battery charge level is graphed in real time. The percentage charge level (0-100%) is shown on the vertical (Y) axis...",""],
["hid_external.htm","External interfaces","External Interfaces BurnInTest Interface BatteryMon can work with another product from PassMark Software called, BurnInTest. If you have BurnInTes...",""],
["hid_faq.htm","Problems and FAQ","Problems and Frequently Asked Questions (FAQ) Note: See the PassMark website (www.passmark.com) for the latest version of the FAQ Q. How accurate ...",""],
["hid_logfile.htm","Logging data","Log file The last 1000 samples are logged in memory by BatteryMon. Clicking on the view log button will create a log file on the disk and start up...",""],
["hid_mini.htm","The Mini Window","The Mini Window To use the mini window function, make sure BatteryMon is currently sampling by clicking the ’Start’ button. Next double click the ...",""],
["hid_ordering.htm","Purchasing information","Purchasing information Price Free for personal use, for commercial use $USD 24 (single commercial user licence) Purchase Online from the PassMark ...",""],
["hid_overview.htm","Introduction and Overview","BatteryMon by PassMark Software - Overview BatteryMon is an easy to use Windows based application that allows users to monitor the performance of ...",""],
["hid_systemreq.htm","System requirements","System Requirements Pentium 100Mhz or faster. Windows 98, WinMe, Windows 2000, XP, 2003, Vista, 7, 8 and 10 (Windows 95 and NT are not supported) ...",""],
["hid_whats_new.htm","What&#39;s new","What&#39;s New - Version history Version 2.1 Build 1008 25/03/2013 Removed licensing and release as free for personal use, a company licence is requir...",""],
["serialinterface.htm","Serial Interface","Serial Interface BatteryMon is able to read information about a battery that is connected via the serial port. However due to the fact that there ...",""],
["systeminfo.htm","System Info","System Information Processor Type – The type of the detected processor. Calculated Processor Speed – The processor speed as calculated by BatteryM...",""],
["systeminfo_2.htm","Charge/Discharge Units","Charge/Discharge Units Where possible the charge and discharge rate is given in milli-Watts. However, due to the limitations of some batteries thi...",""]];
